### ISSUE TITLE
Line Subtotals Tax Display setting not used when displaying order line subtotal

### ISSUE THREAD

**Issue by andrelillvede** [ayudoo/odoo_business_relationships#1]
Odoo 15
odoo_business_relationships:ddf91f2

Settings -> Accounting -> Customer Invoices -> Line Subtotals Tax Display is checked and set to "Business Relationship Dependent"

Contacts -> Business Relationships -> B2B -> Line Subtotals Tax Display is set to "Tax-excluded"

On sales order line on order with B2B contact the subtotal is incorrectly shown with VAT included. Unit price is displayed correctly without VAT included.

**Comment by mjrk** [comment]
@andrelillvede

There is some fix for the inactive internal users, and internal users have tax_excluded as setting now. I also updated the README. Either you configure it accordingly, or you uninstall and install the app again.

Please note:

Odoo displays the price of the pricelist as unit price (or the list price). The tax display setting just changes the line total/subtotal display. Thus, that the unit price and line price can differ is the default behavior.  

There are two types of taxes: `Included in Price` or not. Opening a tax configuration, you see it under `Advanced Options`.
If you choose `tax_included` line display together with taxes `Included in Price` both values, unit price and line total do match (for quantity 1, of course). 
The same for the other way around: `tax_excluded` line display and using taxes not `included in price`. For this to work, you also need at least 2 prices for the products, one with, and one without taxes included, finally, with fiscal positions they are matched together. You find the detailed description in the link posted above. But if you configure it differently, it cannot match.

The reason for all this configuration freedom and hassle is rounding imprecision, that can lead to fiscal issues or "ugly" prices. Just how the world is.

With this module it is easier to maintain - you don't need to do it for every customer individually, but can assign pricelists and fiscal positions according to business relationship types and delivery addresses. It's more a side effect, that you can show tax excluded prices in your shop and cart pages for B2B users. However, quite often it's on the wishlist, and as this, an important addition.

I hope, this clarifies the topic to you. Let me know, if you have legal requirements that cannot be solved or configured. Knowing the details of your requirements, I might be able to plan an extension module.  

Or if we can simply close this issue.

**Comment by gusplil** [comment]
@mjrk 

We dont necessarily need to have different tax displays in the backend. The problem we are facing is that the printed reports (pdf) will display subtotals as per the settings the internal user is using instead of what we set on the selected customer.

What we would like is to be able to display incl vat on unit price and subtotals for b2c and excl vat on unit price and subtotals for b2b both on website, portal and printed reports

**Comment by mjrk** [comment]
@andrelillvede 

Unit Price

Regarding the unit price, as mentioned before, you need to configure your prices accordingly: vat included prices (pricelists) for b2c with taxes included in the price, and vat excluded prices (pricelists) for b2b with the usual default tax settings. That is the current state of Odoo. There is no field "unit price without taxes" because the unit price is fiscal position and tax settings independent. Overriding all these parts is out of the scope of this module for the time being - and it is even a totally different feature. We have to consider here, that a tax dependent unit price could lead to rounding imprecision or rounding inconsistencies. It it's not a display issue, but a fiscal/calculation one, and that's why it has to be configured in the way described above.

Line totals

However, to display the line sum price as subtotal (B2B) and total (B2C) in the document layouts is clearly a desirable feature and useful extension. I will look at it this week anyway and keep you updated. In current use cases it was OK for B2C customers to see the unit price with taxes, but the line total without, in the context of above pricelist configuration. 
Another idea was to show both columns, when "business relationship dependent" tax display is used. This would be the simplest and most generic solution. Would this satisfy your requirements, too?

Are you talking just about the invoice PDFs or are there other PDFs, too?

**Comment by gusplil** [comment]
Unit price we have configured so it works as per documentation, problem is the subtotals that we wish to be consistant with b2b & b2c tax display. Pdf reports that is affected is order confirmation and invoice. 

A situation where b2c customer see everything including vat on website / portal / cart but get a mixed order confirmation / invoice pdf would just add confusion.

Having two columns for line total showing incl & excl vat could be a solution even though it would be a cleaner to have only one.

**Comment by mjrk** [comment]
Thanks a lot for your feedback.

I will discuss the topic with other parties and come back to this as soon as possible during this week.

**Comment by andrelillvede** [comment]
Thank you for taking your time to clarify the intended behaviour and listening to our concerns, it is much appreciated.
We look forward to hearing what your discussions will come to.

**Comment by mjrk** [comment]
@andrelillvede 

There is an update available which might solve your problem. And, luckily, it comes around without overriding odoo email or report templates. The solution also solves another requirement: to be able to assign salesperson (and team) according to the business relationshop with the customer.

Here is what you need to know: the odoo email templates for sales order confirmation display taxes according to the salesperson of the order. Thus, if you assign "My B2C Shop" (any contact of type B2C will do it) as default salesperson for B2C customers, the email templates will already be correct. 

Unfortunately, the report PDFs are generated in the user context of OdooBot. I added an experimental module salesperson_report_context. It runs PDF generation for sales orders and invoices with the salesperson as running user (instead of the Bot) and that works like charm for our requirements. 

Please let me know, if it works for you, too!

**Comment by mjrk** [comment]
@gusplil @andrelillvede 

As some weeks passed by, did you have the opportunity to validate the solution for your use case? If questions arise, don't hesitate to ask.

Else, I'll soon close the issue because the solution described above works for us.

**Comment by andrelillvede** [comment]
Hi!
Sorry for the late reply, we have been busy working on other parts of our odoo implementation.

We ended up going another route and modified the reports and views to reflect the correct vat display based on the customer.

Thank you for your time and work on trying to accomodate our needs.

**Comment by mjrk** [comment]
@andrelillvede Thanks for your reply! 

I worked on this part anyway. The solution solved most required mail and report customization, and made it consistent with Odoo standard, if required. 

If you send sale order email confirmation without customizing the mail template's lines, you still might have to configure the salesperson accordingly.
